<div>
    <img src="https://miro.medium.com/v2/resize:fit:1181/1*5aFr82kqA3lsHx-KgwIP3w.jpeg" 
         width="150" style="float: left; margin-right: 20px;">
    <h1 style="line-height: 150px; margin: 0;">How does a bike-share navigate speedy success?</h1>
    <div style="clear: both;"></div>
</div>

This project is part of the course **Google Data Analytics** where I’ll perform typical tasks of a junior data analyst while following the steps of the data analysis process: **Ask**, **Prepare**, **Process**, **Analyze**, **Share**, and **Act**.

### Scenario

You are a junior data analyst working on the marketing analyst team at Cyclistic, a bike-share company in Chicago. The director of marketing believes the company’s future success depends on maximizing the number of annual memberships. Therefore, your team wants to understand how casual riders and annual members use Cyclistic bikes differently. From these insights, your team will design a new marketing strategy to convert casual riders into annual members. But first, Cyclistic executives must approve your recommendations, so they must be backed up with compelling data insights and professional data visualizations.

### Ask

According to the finance analysts at Cyclistic, annual members generate significantly more profit than casual riders. As a result, the company’s primary business objective is to increase the number of annual memberships by converting existing casual riders into members.

To achieve this goal, the marketing analytics team must first understand the behavioral differences between annual members and casual riders. Identifying these differences will provide data-driven insights to support the development of targeted marketing strategies.

Three key questions will guide the future marketing program:
1. How do annual members and casual riders use Cyclistic bikes differently?
2. Why would casual riders purchase Cyclistic annual memberships?
3. How can Cyclistic use digital media to influence casual riders to become members?

For this analysis, the focus will be on answering the first question:
**How do annual members and casual riders use Cyclistic bikes differently?**

### Prepare 

For this project, the data is located inside the [data](data/) folder, which consists in two subfolder:

- **[zipped](data/zipped)** - Where is stored the .zip files.
- **[raw](data/raw/)** - Where is stored the raw files extracted from the zip files.

Each `.csv` file represents a month of the the year (2025) that we are going to analyze.

The data has been made available by *Motivate International Inc*. under this [license](https://www.divvybikes.com/data-license-agreement).

The dataset contains the following colmuns:
- ride_id
- rideable_type
- started_at
- ended_at
- start_station_name
- start_station_id
- end_station_name
- end_station_id
- start_lat
- start_lng
- end_lat
- end_lng
- member_casual

### Process 

For this project I'm going to use Python and Jupyter Notebook, because is a proper language and it's good for documentation steps of the analysis.

In [1]:
# import libraries
import requests
import pandas as pd 
import json
import matplotlib.pyplot as plt

In [2]:
# read each file, transform into a dataset and put inside of a list
dfs = []

for file in range(1,13):
    filepath = f'data/raw/2025{file:02}-divvy-tripdata.csv' # data source
    try:
        df_raw = pd.read_csv(filepath, delimiter=',')
        if df_raw.empty:
            print("WARNING: The Dataframe is empty")
        else:
            dfs.append(df_raw)
    except Exception as e:
        print(e)

In [3]:
# Display each dataset
for i in range(len(dfs)):
    display(dfs[i].head())

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,7569BC890583FCD7,classic_bike,2025-01-21 17:23:54.538,2025-01-21 17:37:52.015,Wacker Dr & Washington St,KA1503000072,McClurg Ct & Ohio St,TA1306000029,41.883143,-87.637242,41.892592,-87.617289,member
1,013609308856B7FC,electric_bike,2025-01-11 15:44:06.795,2025-01-11 15:49:11.139,Halsted St & Wrightwood Ave,TA1309000061,Racine Ave & Belmont Ave,TA1308000019,41.929147,-87.649153,41.939743,-87.658865,member
2,EACACD3CE0607C0D,classic_bike,2025-01-02 15:16:27.730,2025-01-02 15:28:03.230,Southport Ave & Waveland Ave,13235,Broadway & Cornelia Ave,13278,41.948226,-87.664071,41.945529,-87.646439,member
3,EAA2485BA64710D3,classic_bike,2025-01-23 08:49:05.814,2025-01-23 08:52:40.047,Southport Ave & Waveland Ave,13235,Southport Ave & Roscoe St,13071,41.948226,-87.664071,41.943739,-87.664020,member
4,7F8BE2471C7F746B,electric_bike,2025-01-16 08:38:32.338,2025-01-16 08:41:06.767,Southport Ave & Waveland Ave,13235,Southport Ave & Roscoe St,13071,41.948226,-87.664071,41.943739,-87.664020,member

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,A246CA24873F7C5C,classic_bike,2025-02-25 21:21:21.171,2025-02-25 21:30:09.941,Michigan Ave & Lake St,TA1305000011,Clark St & Elm St,TA1307000039,41.886022,-87.624398,41.902973,-87.631280,member
1,303C0906F3F068AE,classic_bike,2025-02-08 14:55:13.493,2025-02-08 15:13:39.890,Ogden Ave & Race Ave,13194,Clark St & Elm St,TA1307000039,41.891795,-87.658751,41.902973,-87.631280,member
2,A0F65F3531F1FB2B,electric_bike,2025-02-24 00:32:56.553,2025-02-24 00:38:21.711,Michigan Ave & Lake St,TA1305000011,Wabash Ave & 9th St,TA1309000010,41.886022,-87.624398,41.870769,-87.625734,casual
3,CE663C815B6A6D73,electric_bike,2025-02-07 17:00:38.646,2025-02-07 17:34:29.012,Ogden Ave & Race Ave,13194,Clark St & Elm St,TA1307000039,41.891795,-87.658751,41.902973,-87.631280,casual
4,43F626BEF919D026,classic_bike,2025-02-10 14:56:56.565,2025-02-10 15:01:18.745,Clark St & North Ave,13128,Clark St & Elm St,TA1307000039,41.911974,-87.631942,41.902973,-87.631280,member

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,16CBE9844D401954,electric_bike,2025-03-18 08:39:20.065,2025-03-18 08:51:37.633,NaN,NaN,Canal St & Jackson Blvd,13138,41.91,-87.67,41.878125,-87.639968,member
1,1CB408029E2B5F74,electric_bike,2025-03-24 16:04:22.239,2025-03-24 16:27:41.347,NaN,NaN,Albany Ave & Bloomingdale Ave,15655,41.86,-87.68,41.914027,-87.705126,member
2,7B6A76CD0F204D08,electric_bike,2025-03-10 16:06:19.708,2025-03-10 16:29:17.457,NaN,NaN,Albany Ave & Bloomingdale Ave,15655,41.86,-87.68,41.914027,-87.705126,member
3,4F7084E3D75CDE31,electric_bike,2025-03-21 14:28:14.579,2025-03-21 14:35:06.160,NaN,NaN,Canal St & Jackson Blvd,13138,41.87,-87.63,41.878125,-87.639968,member
4,E419A570A5A0475B,electric_bike,2025-03-14 17:54:14.484,2025-03-14 18:17:53.254,NaN,NaN,Albany Ave & Bloomingdale Ave,15655,41.89,-87.67,41.914027,-87.705126,casual

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,AF3863596DF9D94B,classic_bike,2025-04-27 14:29:34.619,2025-04-27 14:36:23.584,Troy St & Elston Ave,15631,Richmond St & Diversey Ave,15645,41.945244,-87.706650,41.931902,-87.701195,member
1,8B38081EBE918800,electric_bike,2025-04-23 17:48:51.863,2025-04-23 17:59:06.015,Wabash Ave & Adams St,KA1503000015,Green St & Madison St,TA1307000120,41.879472,-87.625689,41.881859,-87.649264,member
2,1C7F1DE826BBBC8D,electric_bike,2025-04-05 17:55:30.845,2025-04-05 18:05:40.032,Damen Ave & Cortland St,13133,California Ave & Fletcher St,15642,41.915983,-87.677335,41.938429,-87.698008,member
3,CAD23D69A79A6C3B,classic_bike,2025-04-03 08:22:04.493,2025-04-03 08:32:06.099,Clark St & Elm St,TA1307000039,Orleans St & Merchandise Mart Plaza,TA1305000022,41.902973,-87.631280,41.888243,-87.636390,member
4,BE241E601482E0AB,electric_bike,2025-04-15 06:09:55.293,2025-04-15 06:19:58.942,Western Ave & Walton St,KA1504000103,Damen Ave & Charleston St,13288,41.898418,-87.686596,41.920082,-87.677855,member

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,BADF67E2C5058F19,classic_bike,2025-05-11 17:22:39.471,2025-05-11 18:11:19.249,DuSable Lake Shore Dr & North Blvd,LF-005,Winthrop Ave & Lawrence Ave,TA1308000021,41.911722,-87.626804,41.968812,-87.657659,member
1,0210AE485D59C8C5,electric_bike,2025-05-05 08:02:09.251,2025-05-05 08:12:07.549,Damen Ave & Grand Ave,TA1308000006,Desplaines St & Jackson Blvd,15539,41.892394,-87.676885,41.878119,-87.643948,member
2,5E68FE5B9283E4C4,classic_bike,2025-05-02 10:32:33.062,2025-05-02 10:39:07.262,LaSalle St & Illinois St,13430,Clark St & Elm St,TA1307000039,41.890762,-87.631697,41.903322,-87.632999,member
3,13D2DCD6FB872858,classic_bike,2025-05-12 11:12:16.579,2025-05-12 11:17:25.126,Milwaukee Ave & Rockwell St,13242,Damen Ave & Cortland St,13133,41.920330,-87.693090,41.915983,-87.677335,member
4,F04DF9EE163351DD,classic_bike,2025-05-01 10:13:36.821,2025-05-01 10:17:40.548,Halsted St & Roosevelt Rd,TA1305000017,Clinton St & Roosevelt Rd,WL-008,41.867324,-87.648625,41.867118,-87.641088,member

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,0E43949BF937C7DA,electric_bike,2025-06-05 21:24:56.104,2025-06-05 21:38:44.446,Clark St & Armitage Ave,CHI00474,Dearborn Pkwy & Delaware Pl,CHI00306,41.918306,-87.636282,41.898969,-87.629912,member
1,1CDEA40FEAF21789,classic_bike,2025-06-14 13:03:34.478,2025-06-14 13:13:19.791,Dearborn Pkwy & Delaware Pl,CHI00306,Kingsbury St & Kinzie St,CHI00299,41.898969,-87.629912,41.889177,-87.638506,member
2,7ECEB1638575575C,classic_bike,2025-06-09 13:30:22.540,2025-06-09 13:39:53.640,Dearborn Pkwy & Delaware Pl,CHI00306,Kingsbury St & Kinzie St,CHI00299,41.898969,-87.629912,41.889177,-87.638506,member
3,F275084E25F5A131,electric_bike,2025-06-15 12:48:13.321,2025-06-15 13:00:18.798,Clark St & Elm St,CHI00281,NaN,NaN,41.902970,-87.631300,41.920000,-87.650000,member
4,F42E81C85AC722FB,electric_bike,2025-06-19 07:54:26.103,2025-06-19 08:04:36.583,Damen Ave & Cortland St,CHI00388,NaN,NaN,41.915983,-87.677335,41.940000,-87.690000,member

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,455D43BD91D73437,classic_bike,2025-07-05 17:15:08.456,2025-07-05 17:25:47.079,Lincoln Ave & Diversey Pkwy,CHI00285,Lincoln Ave & Addison St,CHI00478,41.932225,-87.658617,41.946176,-87.673308,member
1,9D4A6B723ECD98CA,classic_bike,2025-07-01 13:57:38.878,2025-07-01 14:06:35.780,Cottage Grove Ave & Oakwood Blvd,CHI00400,Cottage Grove Ave & 47th St,CHI00488,41.822985,-87.607100,41.809855,-87.606755,member
2,C57044CF523302ED,classic_bike,2025-07-31 16:49:28.142,2025-07-31 17:15:28.999,Theater on the Lake,CHI00420,Winthrop Ave & Lawrence Ave,CHI00391,41.926277,-87.630834,41.968812,-87.657659,member
3,AFD35552E6685B6E,electric_bike,2025-07-17 09:36:21.058,2025-07-17 09:46:54.706,Pine Grove Ave & Waveland Ave,CHI00354,Winthrop Ave & Lawrence Ave,CHI00391,41.949473,-87.646453,41.968812,-87.657659,member
4,C0582EBAA6CED519,classic_bike,2025-07-02 18:43:45.213,2025-07-02 18:57:06.687,Theater on the Lake,CHI00420,Sheffield Ave & Wellington Ave,CHI00274,41.926277,-87.630834,41.936253,-87.652662,member

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,5C00A6B5A60E4AFC,electric_bike,2025-08-28 15:56:46.803,2025-08-28 16:11:54.890,NaN,NaN,NaN,NaN,41.88,-87.64,41.89,-87.62,casual
1,FB25D4B923656D01,electric_bike,2025-08-27 19:15:53.059,2025-08-27 19:34:13.683,NaN,NaN,NaN,NaN,41.95,-87.64,41.89,-87.61,casual
2,C665B0EC937C860C,electric_bike,2025-08-27 20:27:31.394,2025-08-27 20:38:29.890,NaN,NaN,NaN,NaN,41.92,-87.65,41.90,-87.64,casual
3,C68C54D5FD9717C2,electric_bike,2025-08-28 15:33:21.055,2025-08-28 15:39:58.052,NaN,NaN,NaN,NaN,41.89,-87.65,41.88,-87.65,casual
4,902D69C29B0E65F8,electric_bike,2025-08-28 09:59:44.846,2025-08-28 10:11:17.343,NaN,NaN,NaN,NaN,41.98,-87.68,41.95,-87.70,casual

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,B0AD82B8A2556E7C,electric_bike,2025-09-01 12:05:13.323,2025-09-01 12:25:19.273,NaN,NaN,NaN,NaN,41.91,-87.63,41.96,-87.64,member
1,DCC4ABF0F7DCCE6A,electric_bike,2025-09-01 01:41:00.775,2025-09-01 01:48:59.228,NaN,NaN,NaN,NaN,41.95,-87.67,41.95,-87.65,member
2,C27785FFE7568433,electric_bike,2025-09-01 07:16:13.921,2025-09-01 07:39:51.831,NaN,NaN,NaN,NaN,41.94,-87.65,41.98,-87.65,member
3,812DB2D3AD2F18EB,electric_bike,2025-09-01 09:31:36.294,2025-09-01 09:49:08.022,NaN,NaN,NaN,NaN,41.98,-87.65,41.94,-87.65,member
4,61F6BD3174DC4E84,electric_bike,2025-09-26 08:51:58.069,2025-09-26 09:07:29.290,NaN,NaN,NaN,NaN,41.90,-87.69,41.87,-87.65,member

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,AAED255E1310E516,classic_bike,2025-10-27 08:19:53.208,2025-10-27 08:25:53.481,Wells St & Polk St,CHI00606,Franklin St & Washington St,CHI02074,41.872732,-87.633516,41.883180,-87.635110,member
1,F90C86BF3BB85040,classic_bike,2025-10-14 07:42:55.465,2025-10-14 08:04:08.663,Racine Ave & Wrightwood Ave,CHI00506,McClurg Ct & Ohio St,CHI00330,41.928887,-87.658971,41.892592,-87.617289,member
2,90429D9729A3EE8E,classic_bike,2025-10-12 08:18:23.613,2025-10-12 08:28:38.983,Clinton St & 18th St,CHI00235,Desplaines St & Jackson Blvd,CHI00518,41.857950,-87.640826,41.878119,-87.643948,casual
3,C8433F9B78A1E63D,electric_bike,2025-10-14 07:45:56.471,2025-10-14 08:07:24.447,Pine Grove Ave & Irving Park Rd,CHI00482,Wells St & Huron St,CHI00294,41.954398,-87.647997,41.894795,-87.634374,member
4,62F3C413C442C154,electric_bike,2025-10-19 10:08:45.138,2025-10-19 10:12:34.771,Pine Grove Ave & Irving Park Rd,CHI00482,Sheridan Rd & Montrose Ave,CHI00290,41.954365,-87.647929,41.961670,-87.654640,member

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,E555D9F8E9C2F56B,electric_bike,2025-11-04 00:09:07.792,2025-11-04 00:15:04.661,NaN,NaN,NaN,NaN,41.94,-87.67,41.94,-87.67,casual
1,EAEBE70DBF015886,electric_bike,2025-11-04 14:32:09.067,2025-11-04 14:36:43.998,NaN,NaN,NaN,NaN,41.90,-87.64,41.91,-87.64,casual
2,A42F8404F804E56E,electric_bike,2025-11-04 12:20:48.215,2025-11-04 12:21:01.630,NaN,NaN,NaN,NaN,41.89,-87.63,41.89,-87.63,casual
3,E49D01E38A1E074E,electric_bike,2025-11-04 12:17:16.548,2025-11-04 12:17:51.527,NaN,NaN,NaN,NaN,41.89,-87.63,41.89,-87.63,casual
4,9308F609195D2414,electric_bike,2025-11-04 08:16:27.979,2025-11-04 08:21:02.780,NaN,NaN,NaN,NaN,41.89,-87.64,41.88,-87.64,casual

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,D90034EFC7235A41,electric_bike,2025-12-22 17:20:27.872,2025-12-22 17:27:29.937,Broadway & Berwyn Ave,CHI00414,Broadway & Sunnyside Ave,CHI02089,41.978361,-87.659789,41.963419,-87.656069,member
1,B005230EE77A29D0,classic_bike,2025-12-20 17:15:31.749,2025-12-20 17:20:07.746,Sheridan Rd & Montrose Ave,CHI00290,Broadway & Sheridan Rd,CHI00476,41.961670,-87.654640,41.952833,-87.649993,member
2,FD33124F2231E215,classic_bike,2025-12-06 13:38:18.275,2025-12-06 13:52:54.682,Southport Ave & Wrightwood Ave,CHI00339,Larrabee St & Menomonee St,CHI00262,41.928773,-87.663913,41.914680,-87.643320,casual
3,7363165DB4BD6D14,electric_bike,2025-12-16 20:58:28.703,2025-12-16 21:04:35.476,Sheridan Rd & Montrose Ave,CHI00290,Clark St & Newport St,CHI00674,41.961670,-87.654640,41.944540,-87.654678,member
4,F09F745E43DF9556,electric_bike,2025-12-09 14:53:43.347,2025-12-09 14:58:30.944,Larrabee St & Kingsbury St 1,CHI00245,Rush St & Superior St,CHI00368,41.897764,-87.642884,41.895765,-87.625908,member

In [4]:
# I'm going to use the first dataset columns as pattern for all data
dfs[0].columns

Index(['ride_id', 'rideable_type', 'started_at', 'ended_at',
       'start_station_name', 'start_station_id', 'end_station_name',
       'end_station_id', 'start_lat', 'start_lng', 'end_lat', 'end_lng',
       'member_casual'],
      dtype='object')

So let's check if all the dataset is followng the pattern

In [5]:
for col in range(len(dfs)):
    print(f"==== Dataset {col} ====")
    pattern_col = list(dfs[0].columns)
    comparison_col = list(dfs[col].columns)
    for i in range(len(pattern_col)):
        if comparison_col[i] == pattern_col[i]: 
            continue
        else:
            print(f"The columns {i} is different: \n Col from {dfs[col]}{comparison_col[i]} \n Pattern col: {pattern_col[i]}")
    print("All columns are equal!")

==== Dataset 0 ====
All columns are equal!
==== Dataset 1 ====
All columns are equal!
==== Dataset 2 ====
All columns are equal!
==== Dataset 3 ====
All columns are equal!
==== Dataset 4 ====
All columns are equal!
==== Dataset 5 ====
All columns are equal!
==== Dataset 6 ====
All columns are equal!
==== Dataset 7 ====
All columns are equal!
==== Dataset 8 ====
All columns are equal!
==== Dataset 9 ====
All columns are equal!
==== Dataset 10 ====
All columns are equal!
==== Dataset 11 ====
All columns are equal!

It's all good in here!
So now let's concat all data.

In [6]:
df_concat = pd.concat(dfs, ignore_index=True)
df_concat.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,7569BC890583FCD7,classic_bike,2025-01-21 17:23:54.538,2025-01-21 17:37:52.015,Wacker Dr & Washington St,KA1503000072,McClurg Ct & Ohio St,TA1306000029,41.883143,-87.637242,41.892592,-87.617289,member
1,013609308856B7FC,electric_bike,2025-01-11 15:44:06.795,2025-01-11 15:49:11.139,Halsted St & Wrightwood Ave,TA1309000061,Racine Ave & Belmont Ave,TA1308000019,41.929147,-87.649153,41.939743,-87.658865,member
2,EACACD3CE0607C0D,classic_bike,2025-01-02 15:16:27.730,2025-01-02 15:28:03.230,Southport Ave & Waveland Ave,13235,Broadway & Cornelia Ave,13278,41.948226,-87.664071,41.945529,-87.646439,member
3,EAA2485BA64710D3,classic_bike,2025-01-23 08:49:05.814,2025-01-23 08:52:40.047,Southport Ave & Waveland Ave,13235,Southport Ave & Roscoe St,13071,41.948226,-87.664071,41.943739,-87.664020,member
4,7F8BE2471C7F746B,electric_bike,2025-01-16 08:38:32.338,2025-01-16 08:41:06.767,Southport Ave & Waveland Ave,13235,Southport Ave & Roscoe St,13071,41.948226,-87.664071,41.943739,-87.664020,member

In [7]:
df_concat.describe()

          start_lat     start_lng       end_lat       end_lng
count  5.552994e+06  5.552994e+06  5.547459e+06  5.547459e+06
mean   4.190366e+01 -8.764648e+01  4.190411e+01 -8.764683e+01
std    4.443323e-02  2.726130e-02  4.460469e-02  2.746640e-02
min    4.164850e+01 -8.789000e+01  4.149000e+01 -8.810000e+01
25%    4.188213e+01 -8.766000e+01  4.188241e+01 -8.766000e+01
50%    4.189859e+01 -8.764177e+01  4.189964e+01 -8.764275e+01
75%    4.193000e+01 -8.762991e+01  4.193000e+01 -8.763000e+01
max    4.207000e+01 -8.752000e+01  4.221000e+01 -8.742000e+01

In [8]:
df_concat.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5552994 entries, 0 to 5552993
Data columns (total 13 columns):
 #   Column              Dtype
---  ------              -----
 0   ride_id             object
 1   rideable_type       object
 2   started_at          object
 3   ended_at            object
 4   start_station_name  object
 5   start_station_id    object
 6   end_station_name    object
 7   end_station_id      object
 8   start_lat           float64
 9   start_lng           float64
 10  end_lat             float64
 11  end_lng             float64
 12  member_casual       object
dtypes: float64(4), object(9)
memory usage: 550.8+ MB

In [9]:
# transforming datetime columns 
df_concat['started_at'] = pd.to_datetime(df_concat['started_at'], format="%Y-%m-%d %H:%M:%S.%f")
df_concat['ended_at'] = pd.to_datetime(df_concat['ended_at'], format="%Y-%m-%d %H:%M:%S.%f")

print(f"started_at: {df_concat['started_at'].dtypes}")
print(f"ended_at: {df_concat['ended_at'].dtypes}")

started_at: datetime64[ns]
ended_at: datetime64[ns]

In [10]:
# creating column 'trip_duration'
df_concat['trip_duration_seconds'] = (df_concat['ended_at'] - df_concat['started_at']).dt.total_seconds().astype(int)

# creating column 'day of week'
df_concat['day_of_week'] = df_concat['started_at'].dt.day_name()

# creating each column for date 
df_concat['date'] = df_concat['started_at'].dt.date
df_concat['day'] = df_concat['started_at'].dt.day
df_concat['month'] = df_concat['started_at'].dt.month
df_concat['year'] = df_concat['started_at'].dt.year

df_concat.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,trip_duration_seconds,day_of_week,date,day,month,year
0,7569BC890583FCD7,classic_bike,2025-01-21 17:23:54.538,2025-01-21 17:37:52.015,Wacker Dr & Washington St,KA1503000072,McClurg Ct & Ohio St,TA1306000029,41.883143,-87.637242,41.892592,-87.617289,member,837,Tuesday,2025-01-21,21,1,2025
1,013609308856B7FC,electric_bike,2025-01-11 15:44:06.795,2025-01-11 15:49:11.139,Halsted St & Wrightwood Ave,TA1309000061,Racine Ave & Belmont Ave,TA1308000019,41.929147,-87.649153,41.939743,-87.658865,member,304,Saturday,2025-01-11,11,1,2025
2,EACACD3CE0607C0D,classic_bike,2025-01-02 15:16:27.730,2025-01-02 15:28:03.230,Southport Ave & Waveland Ave,13235,Broadway & Cornelia Ave,13278,41.948226,-87.664071,41.945529,-87.646439,member,695,Thursday,2025-01-02,2,1,2025
3,EAA2485BA64710D3,classic_bike,2025-01-23 08:49:05.814,2025-01-23 08:52:40.047,Southport Ave & Waveland Ave,13235,Southport Ave & Roscoe St,13071,41.948226,-87.664071,41.943739,-87.664020,member,214,Thursday,2025-01-23,23,1,2025
4,7F8BE2471C7F746B,electric_bike,2025-01-16 08:38:32.338,2025-01-16 08:41:06.767,Southport Ave & Waveland Ave,13235,Southport Ave & Roscoe St,13071,41.948226,-87.664071,41.943739,-87.664020,member,154,Thursday,2025-01-16,16,1,2025

In [11]:
# Checking data info
df_concat.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5552994 entries, 0 to 5552993
Data columns (total 19 columns):
 #   Column                 Dtype
---  ------                 -----
 0   ride_id                object
 1   rideable_type          object
 2   started_at             datetime64[ns]
 3   ended_at               datetime64[ns]
 4   start_station_name     object
 5   start_station_id       object
 6   end_station_name       object
 7   end_station_id         object
 8   start_lat              float64
 9   start_lng              float64
 10  end_lat                float64
 11  end_lng                float64
 12  member_casual          object
 13  trip_duration_seconds  int32
 14  day_of_week            object
 15  date                   object
 16  day                    int32
 17  month                  int32
 18  year                   int32
dtypes: datetime64[ns](2), float64(4), int32(4), object(9)
memory usage: 720.2+ MB

In [12]:
# Checking if have duplicated rides
df_concat['ride_id'].duplicated().sum()

0

In [13]:
#Checking unique values
df_concat.nunique()

ride_id                  5552994
rideable_type                  2
started_at               5551938
ended_at                 5550528
start_station_name          1893
start_station_id            3360
end_station_name            1901
end_station_id              3383
start_lat                 118725
start_lng                 116911
end_lat                     2030
end_lng                     2028
member_casual                  2
trip_duration_seconds      19149
day_of_week                    7
date                         366
day                           31
month                         12
year                           2
dtype: int64

In [14]:
#Checking for null values

df_concat.isna().sum()

ride_id                        0
rideable_type                  0
started_at                     0
ended_at                       0
start_station_name       1184673
start_station_id         1184673
end_station_name         1243305
end_station_id           1243305
start_lat                      0
start_lng                      0
end_lat                     5535
end_lng                     5535
member_casual                  0
trip_duration_seconds          0
day_of_week                    0
date                           0
day                            0
month                          0
year                           0
dtype: int64

Now let's remove all the bad data.

In [15]:
# drop null values

df_concat.dropna()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,trip_duration_seconds,day_of_week,date,day,month,year
0,7569BC890583FCD7,classic_bike,2025-01-21 17:23:54.538,2025-01-21 17:37:52.015,Wacker Dr & Washington St,KA1503000072,McClurg Ct & Ohio St,TA1306000029,41.883143,-87.637242,41.892592,-87.617289,member,837,Tuesday,2025-01-21,21,1,2025
1,013609308856B7FC,electric_bike,2025-01-11 15:44:06.795,2025-01-11 15:49:11.139,Halsted St & Wrightwood Ave,TA1309000061,Racine Ave & Belmont Ave,TA1308000019,41.929147,-87.649153,41.939743,-87.658865,member,304,Saturday,2025-01-11,11,1,2025
2,EACACD3CE0607C0D,classic_bike,2025-01-02 15:16:27.730,2025-01-02 15:28:03.230,Southport Ave & Waveland Ave,13235,Broadway & Cornelia Ave,13278,41.948226,-87.664071,41.945529,-87.646439,member,695,Thursday,2025-01-02,2,1,2025
3,EAA2485BA64710D3,classic_bike,2025-01-23 08:49:05.814,2025-01-23 08:52:40.047,Southport Ave & Waveland Ave,13235,Southport Ave & Roscoe St,13071,41.948226,-87.664071,41.943739,-87.664020,member,214,Thursday,2025-01-23,23,1,2025
4,7F8BE2471C7F746B,electric_bike,2025-01-16 08:38:32.338,2025-01-16 08:41:06.767,Southport Ave & Waveland Ave,13235,Southport Ave & Roscoe St,13071,41.948226,-87.664071,41.943739,-87.664020,member,154,Thursday,2025-01-16,16,1,2025
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5552989,53202484E8371237,electric_bike,2025-12-19 13:43:41.793,2025-12-19 13:54:07.779,Sheffield Ave & Kingsbury St,CHI02023,Halsted St & Melrose St,CHI02162,41.910522,-87.653106,41.941120,-87.649070,member,625,Friday,2025-12-19,19,12,2025
5552990,3582BF76707AB2ED,classic_bike,2025-12-27 12:43:48.446,2025-12-27 12:52:45.141,Larrabee St & Webster Ave,CHI00454,Halsted St & Melrose St,CHI02162,41.921822,-87.644140,41.941120,-87.649070,member,536,Saturday,2025-12-27,27,12,2025
5552991,B12D92DF229EFA41,electric_bike,2025-12-20 01:12:39.053,2025-12-20 01:18:55.928,Clarendon Ave & Junior Ter,CHI00395,Halsted St & Melrose St,CHI02162,41.961004,-87.649603,41.941120,-87.649070,casual,376,Saturday,2025-12-20,20,12,2025
5552992,04D5C6C11909ECAE,electric_bike,2025-12-08 16:46:37.496,2025-12-08 16:58:32.762,Lincoln Ave & Waveland Ave,CHI00446,Halsted St & Wrightwood Ave,CHI00504,41.948797,-87.675278,41.929143,-87.649077,member,715,Monday,2025-12-08,8,12,2025
5552993,D2CF23B6D79232B6,classic_bike,2025-12-20 13:08:27.589,2025-12-20 13:13:54.815,Larrabee St & Webster Ave,CHI00454,Halsted St & Wrightwood Ave,CHI00504,41.921822,-87.644140,41.929143,-87.649077,member,327,Saturday,2025-12-20,20,12,2025

In [16]:
df_clean = df_concat[df_concat['trip_duration_seconds'] > 0].copy()
df_clean

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,trip_duration_seconds,day_of_week,date,day,month,year
0,7569BC890583FCD7,classic_bike,2025-01-21 17:23:54.538,2025-01-21 17:37:52.015,Wacker Dr & Washington St,KA1503000072,McClurg Ct & Ohio St,TA1306000029,41.883143,-87.637242,41.892592,-87.617289,member,837,Tuesday,2025-01-21,21,1,2025
1,013609308856B7FC,electric_bike,2025-01-11 15:44:06.795,2025-01-11 15:49:11.139,Halsted St & Wrightwood Ave,TA1309000061,Racine Ave & Belmont Ave,TA1308000019,41.929147,-87.649153,41.939743,-87.658865,member,304,Saturday,2025-01-11,11,1,2025
2,EACACD3CE0607C0D,classic_bike,2025-01-02 15:16:27.730,2025-01-02 15:28:03.230,Southport Ave & Waveland Ave,13235,Broadway & Cornelia Ave,13278,41.948226,-87.664071,41.945529,-87.646439,member,695,Thursday,2025-01-02,2,1,2025
3,EAA2485BA64710D3,classic_bike,2025-01-23 08:49:05.814,2025-01-23 08:52:40.047,Southport Ave & Waveland Ave,13235,Southport Ave & Roscoe St,13071,41.948226,-87.664071,41.943739,-87.664020,member,214,Thursday,2025-01-23,23,1,2025
4,7F8BE2471C7F746B,electric_bike,2025-01-16 08:38:32.338,2025-01-16 08:41:06.767,Southport Ave & Waveland Ave,13235,Southport Ave & Roscoe St,13071,41.948226,-87.664071,41.943739,-87.664020,member,154,Thursday,2025-01-16,16,1,2025
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5552989,53202484E8371237,electric_bike,2025-12-19 13:43:41.793,2025-12-19 13:54:07.779,Sheffield Ave & Kingsbury St,CHI02023,Halsted St & Melrose St,CHI02162,41.910522,-87.653106,41.941120,-87.649070,member,625,Friday,2025-12-19,19,12,2025
5552990,3582BF76707AB2ED,classic_bike,2025-12-27 12:43:48.446,2025-12-27 12:52:45.141,Larrabee St & Webster Ave,CHI00454,Halsted St & Melrose St,CHI02162,41.921822,-87.644140,41.941120,-87.649070,member,536,Saturday,2025-12-27,27,12,2025
5552991,B12D92DF229EFA41,electric_bike,2025-12-20 01:12:39.053,2025-12-20 01:18:55.928,Clarendon Ave & Junior Ter,CHI00395,Halsted St & Melrose St,CHI02162,41.961004,-87.649603,41.941120,-87.649070,casual,376,Saturday,2025-12-20,20,12,2025
5552992,04D5C6C11909ECAE,electric_bike,2025-12-08 16:46:37.496,2025-12-08 16:58:32.762,Lincoln Ave & Waveland Ave,CHI00446,Halsted St & Wrightwood Ave,CHI00504,41.948797,-87.675278,41.929143,-87.649077,member,715,Monday,2025-12-08,8,12,2025
5552993,D2CF23B6D79232B6,classic_bike,2025-12-20 13:08:27.589,2025-12-20 13:13:54.815,Larrabee St & Webster Ave,CHI00454,Halsted St & Wrightwood Ave,CHI00504,41.921822,-87.644140,41.929143,-87.649077,member,327,Saturday,2025-12-20,20,12,2025

In [17]:
# Checking the new dataset
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5551157 entries, 0 to 5552993
Data columns (total 19 columns):
 #   Column                 Dtype
---  ------                 -----
 0   ride_id                object
 1   rideable_type          object
 2   started_at             datetime64[ns]
 3   ended_at               datetime64[ns]
 4   start_station_name     object
 5   start_station_id       object
 6   end_station_name       object
 7   end_station_id         object
 8   start_lat              float64
 9   start_lng              float64
 10  end_lat                float64
 11  end_lng                float64
 12  member_casual          object
 13  trip_duration_seconds  int32
 14  day_of_week            object
 15  date                   object
 16  day                    int32
 17  month                  int32
 18  year                   int32
dtypes: datetime64[ns](2), float64(4), int32(4), object(9)
memory usage: 762.3+ MB

### Analyze 

In this step we will get some answers from the data making some aggregations, calculations and indetifying some trends and relationships.

In [18]:
# Descriptive analysis 
df_clean.describe()

,started_at,ended_at,start_lat,start_lng,end_lat,end_lng,trip_duration_seconds,day,month,year
count,5551157,5551157,5.551157e+06,5.551157e+06,5.545622e+06,5.545622e+06,5.551157e+06,5.551157e+06,5.551157e+06,5.551157e+06
mean,2025-07-20 19:17:33.664293120,2025-07-20 19:33:35.658376704,4.190366e+01,-8.764648e+01,4.190411e+01,-8.764683e+01,9.614948e+02,1.578357e+01,7.126950e+00,2.025000e+03
min,2024-12-31 18:54:41.803000,2025-01-01 00:00:01.447000,4.164850e+01,-8.789000e+01,4.149000e+01,-8.810000e+01,1.000000e+00,1.000000e+00,1.000000e+00,2.024000e+03
25%,2025-05-28 10:58:47.964999936,2025-05-28 11:15:18.502000128,4.188213e+01,-8.766000e+01,4.188241e+01,-8.766000e+01,3.230000e+02,8.000000e+00,5.000000e+00,2.025000e+03
50%,2025-07-26 17:10:28.555000064,2025-07-26 17:30:52.601999872,4.189859e+01,-8.764176e+01,4.189962e+01,-8.764275e+01,5.650000e+02,1.600000e+01,7.000000e+00,2.025000e+03
75%,2025-09-21 05:57:13.249999872,2025-09-21 06:29:20.284000,4.193000e+01,-8.762991e+01,4.193000e+01,-8.763000e+01,9.940000e+02,2.300000e+01,9.000000e+00,2.025000e+03
max,2025-12-31 23:53:24.274000,2025-12-31 23:58:42.046000,4.207000e+01,-8.752000e+01,4.221000e+01,-8.742000e+01,9.449400e+04,3.100000e+01,1.200000e+01,2.025000e+03
std,NaN,NaN,4.443155e-02,2.726030e-02,4.460306e-02,2.746539e-02,3.307482e+03,8.796144e+00,2.622220e+00,3.089898e-03

In [19]:
# Compare members and casual users
df_clean.groupby('member_casual')['trip_duration_seconds'].agg(['mean', 'median', 'max', 'min'])

                      mean  median    max  min
member_casual
casual         1355.794806   684.0  94494    1
member          739.652866   514.0  89998    1

We can see from that, that casual riders uses the bikes for more time

In [20]:
# Order the days of the week for correct sorting for analysis
days_order = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"]
df_clean['day_of_week'] = pd.Categorical(df_clean['day_of_week'],
categories=days_order, ordered=True)

In [21]:
# See the average ride time by each day for members vs casual users
df_clean.groupby(['member_casual', 'day_of_week'], observed=False)['trip_duration_seconds'].mean()

member_casual  day_of_week
casual         Sunday         1568.547506
               Monday         1339.781145
               Tuesday        1191.414959
               Wednesday      1122.888595
               Thursday       1190.356979
               Friday         1350.348766
               Saturday       1515.575880
member         Sunday          818.295086
               Monday          712.859162
               Tuesday         716.841604
               Wednesday       706.750722
               Thursday        713.514133
               Friday          736.406503
               Saturday        808.793506
Name: trip_duration_seconds, dtype: float64

Both of the classes uses bike for more time during the weekend's, but even so, casual riders uses for more time during all week including weekends.

In [22]:
# Analyze ridership data by type and weekday
summary_stats = df_clean.groupby(['member_casual', 'day_of_week'], observed=False).agg(
number_of_rides=('ride_id', 'count'),
average_duration=('trip_duration_seconds', 'mean')
).reset_index()

summary_stats

   member_casual day_of_week  number_of_rides  average_duration
0         casual      Sunday           331642       1568.547506
1         casual      Monday           228183       1339.781145
2         casual     Tuesday           225502       1191.414959
3         casual   Wednesday           221453       1122.888595
4         casual    Thursday           257923       1190.356979
5         casual      Friday           319957       1350.348766
6         casual    Saturday           414034       1515.575880
7         member      Sunday           382190        818.295086
8         member      Monday           502620        712.859162
9         member     Tuesday           562924        716.841604
10        member   Wednesday           550020        706.750722
11        member    Thursday           575847        713.514133
12        member      Friday           528805        736.406503
13        member    Saturday           450057        808.793506

Now that we made all those steps, let's make some more analysis and go to the **Share** phase.

In [27]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5551157 entries, 0 to 5552993
Data columns (total 19 columns):
 #   Column                 Dtype
---  ------                 -----
 0   ride_id                object
 1   rideable_type          object
 2   started_at             datetime64[ns]
 3   ended_at               datetime64[ns]
 4   start_station_name     object
 5   start_station_id       object
 6   end_station_name       object
 7   end_station_id         object
 8   start_lat              float64
 9   start_lng              float64
 10  end_lat                float64
 11  end_lng                float64
 12  member_casual          object
 13  trip_duration_seconds  int32
 14  day_of_week            category
 15  date                   object
 16  day                    int32
 17  month                  int32
 18  year                   int32
dtypes: category(1), datetime64[ns](2), float64(4), int32(4), object(8)
memory usage: 725.3+ MB

In [29]:
df = df_clean.to_csv(f'data/clean/divvy_trip_data_2025.csv', index=False)